# Application bindings
$terminal = uwsm app -- alacritty
$browser = uwsm app -- firefox
$webapp = $browser --app

bindd = SUPER, return, Terminal, exec, $terminal
bindd = SUPER, E, Yazi, exec, $terminal -e yazi
bindd = SUPER, B, Browser, exec, $browser
bindd = SUPER, M, Music, exec, uwsm app -- spotify
bindd = SUPER, N, Neovim, exec, $terminal -e nvim
bindd = SUPER, T, Activity, exec, $terminal -e btop
bindd = SUPER, D, Docker, exec, $terminal -e lazydocker

bindd = SUPER, G, Github, exec, $webapp="https://github.co/lafco"
bindd = SUPER, D, Discord, exec, $webapp="https://discord.com/channels/@me"
bindd = SUPER, S, ChatGPT, exec, $webapp="https://chatgpt.com"
bindd = SUPER, Y, YouTube, exec, $webapp="https://youtube.com"
bindd = SUPER, O, Capacities, exec, uwsm app -- capacities