# See https://wiki.hyprland.org/Configuring/Monitors/
# List current monitors and resolutions possible: hyprctl monitors
# Format: monitor = [port], resolution, position, scale
# You must relaunch Hyprland after changing any envs (use Super+Esc, then Relaunch)

env = GDK_SCALE,1
monitor = eDP-1, 1920x1080@60, 0x0, 1
monitor = HDMI-A-1, 1920x1080@60, -1920x0, 1

# Workspaces
workspace = 1, monitor:HDMI-A-1, default:true
workspace = 2, monitor:eDP-1, default:true
workspace = 3, monitor:eDP-1, persistent:true, on-created-empty: firefox
workspace = 4, monitor:eDP-1
workspace = 5, monitor:HDMI-A-1
workspace = 6, monitor:HDMI-A-1

windowrule = workspace 3, class:firefox
